TypedStringValue error
Error description:
java.lang.IllegalArgumentException: Parameter of type org.springframework.beans.factory.config.TypedStringValue is not supported

Caused by:
- Run "mvn spring-boot:build-image"

Possible solutions:
-